try {
    fn1();
}
catch (err) {
    console.log("Kļūda izpildot fn2.js: " + err);
}